credentials:
  default: &default
    ssh_pub_key: /home/username/.ssh/id_rsa.pub
    remote_user: root
    remote_chef_path: /root/cookbooks

  production:
    <<: *default
    remote_host: 192.168.1.1
    notifications_email: email@example.com
    domain: example.com

chefs:
  - ufw
  - rvm:
      version: 2.5.0
